services:
  - type: web
    name: smartplayers
    runtime: image
    repo: https://github.com/jacqueshade52-beep/smartplayers
    image:
      url: lorisleiva/laravel-docker:8.1
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --port=$PORT --host=0.0.0.0
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true