services:
  - type: web
    name: smartplayers
    runtime: image
    repo: https://github.com/jacqueshade52-beep/smartplayers
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
    startCommand: php artisan serve --port=$PORT --host=0.0.0.0
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr